dingo-gw/dingo

dingo/core/density/unconditional_density_estimation.py, dingo/core/result.py, dingo/core/utils/plotting.py, dingo/gw/importance_sampling/diagnostics.py, dingo/gw/inference/inference_pipeline.py, dingo/gw/inference/visualization.py, pyproject.toml
This replaces chainconsumer with corner for making corner plot, as described in #166. It places a multiple-posterior corner plotting function in `dingo.core.utils.plotting`.
I have tested it in `dingo_pipe`, but not in `inference_pipeline.py` and `diagnostics.py`. Could someone who uses these please test it?
=> Replace chainconsumer with corner

dingo/core/models/posterior_model.py, dingo/gw/training/train_pipeline.py, dingo/gw/training/train_pipeline_condor.py, docs/source/training.md, examples/training/train_settings_init_production.yaml, examples/training/train_settings_init_toy.yaml, examples/training/train_settings_no_gnpe_production.yaml, examples/training/train_settings_no_gnpe_toy.yaml, examples/training/train_settings_production.yaml, examples/training/train_settings_toy.yaml, pyproject.toml
Moved all calls to the `wandb` library into `try`, `except` statements, therefore dropping the requirement to have it installed. Some further improvements were made to use it in a more generic way
=> Wandb import

dingo/gw/gwutils.py
Our `get_mismatch` function `dingo.gw.gwutils` would permanently whiten the input when an ASD was provided, which would lead to downstream bugs if the waveform data is used for anything else after whitening. I fixed this, and also added support for batched data (frequency axis is as always -1).
=> Fix bug in `get_mismatch`

dingo/gw/injection.py, dingo/gw/likelihood.py, dingo/gw/pipe/importance_sampling.py, dingo/gw/pipe/parser.py, dingo/gw/transforms/detector_transforms.py, docs/source/conf.py, docs/source/dingo_pipe.md, examples/is_settings.yaml, examples/pipe/GW150914.ini, pyproject.toml
This pull request adds the ability to marginalize over detector calibration uncertainty to dingo-pipe. This takes place during the importance sampling stage.
It adds the following keys to the INI files:
* calibration-model
* spline-calibration-envelope-dict
* spline-calibration-nodes
* spline-calibration-curves (not present in bilby-pipe)
Usage is explained in the documentation. It should be noted that these have slightly different interpretation than in bilby-pipe, where one typically performs inference over the calibration parameters rather than marginalizing over them.
In addition, there was a small refactoring of the calibration marginalization code to simplify it.
@jonaswildberger You probably need to update #131 to accommodate these additional INI keys.
=> Add calibration uncertainty marginalization to dingo-pipe

dingo/gw/likelihood.py
There was a slight mistake in calculating the calibration marginalized likelihood which showed up in a difference between the offiical bilby samples and dingo's samples. This has now been corrected, the reason for this bug is included in the following calculation:
=> Corrected for calibration marginalized likelihood

dingo/pipe/dag_creator.py, dingo/pipe/data_generation.py, dingo/pipe/importance_sampling.py, dingo/pipe/main.py, dingo/pipe/parser.py, dingo/pipe/plot.py, dingo/pipe/sampling.py
The change made here is a bit lazy, but simply replacing the (bilby_pipe) `logger` with a new one in dingo_pipe code would lead to inconsistent output because we are calling bilby_pipe code in many places and that is using it's own logger. So, to leave the bilby_pipe code unchanged we take their logger and simply rename it.
=> Rename the imported logger to "dingo_pipe"

dingo/core/result.py, dingo/pipe/dag_creator.py, dingo/pipe/main.py, dingo/pipe/nodes/pe_summary_node.py, dingo/pipe/nodes/sampling_node.py, dingo/pipe/parser.py, docs/source/dingo_pipe.md
This makes two additions to dingo_pipe:
* `importance-sample` option (default True). By setting this to False, we can turn off importance sampling.
* `create-summary`. This is taken over from bilby_pipe. It calls PESummary at the end of the run.
=> Add ability to turn off importance sampling, create summary pages

dingo/gw/noise/synthetic/asd_parameterization.py, dingo/gw/noise/synthetic/asd_sampling.py, dingo/gw/noise/synthetic/generate_dataset.py
When the package got renamed from `dingo.gw.noise.synthetic_noise` -> `dingo.gw.noise.synthetic`, the import statements did not get repointed properly.
=> Fix import bug in synthetic noise package

dingo/gw/__init__.py
This is intended to try to resolve an incompatibility between lal / MKL / pytorch, see https://git.ligo.org/lscsoft/lalsuite/-/issues/300#note_680778.
=> Add lal import in `dingo/gw/__init__.py`

dingo/pipe/nodes/importance_sampling_node.py, dingo/pipe/nodes/plot_node.py, dingo/pipe/nodes/sampling_node.py, pyproject.toml
For compatibility with `bilby_pipe >= 1.0.9`, we assumed an attribute of the `Input` class called `disable_hdf5_locking` in #192. However, this introduced an incompatibility with older version of `bilby_pipe`. This new PR simply gives a default attribute value of `None` by accessing via `getattr()`.
I am currently testing with `bilby_pipe = 1.0.7` and `bilby_pipe = 1.1.0`.
=> Restore compatibility for bilby_pipe < 1.0.9

dingo/gw/waveform_generator/waveform_generator.py
For v5 waveforms the spins were not being converted properly. This was due to the fact that the masses did not have the correct dimensions in the `bilby_to_lalsimulation_spins` function.
=> Fix bug in conversion of spin angles to Cartesian spins for new waveform interface (SEOBNRv5PHM)

dingo/gw/waveform_generator/waveform_generator.py, dingo/gw/waveform_generator/wfg_utils.py, pyproject.toml, tests/gw/waveform_generator/test_wfg_m.py
This PR adds a conditioning method for TD modes mimicking the standard behaviour of conditioning routines in LAL and GWSignal, i.e, starting the modes at a lower frequency for tapering not-in-band cycles and adding some extra buffer times.
=> adding new conditioning for td modes

dingo/pipe/data_generation.py, dingo/pipe/main.py, dingo/pipe/parser.py, pyproject.toml
This brings `dingo_pipe` up to date with `bilby_pipe==1.2.1`. The main change is that the data generation step now transfers files over from elsewhere.
Closes #221 
1. When running, I get the following warning, although it still seems work:
```
10:01 dingo_pipe INFO    : Running: gwdatafind.find_urls(site='H', frametype='H1_HOFT_C02', gpsstart=1126259456.4, gpsend=1126259464.4, urltype='osdf', host='https://datafind.ligo.org', )
10:01 dingo_pipe WARNING : Failed to resolve frame files for detector H1
10:01 dingo_pipe INFO    : Running: gwdatafind.find_urls(site='L', frametype='L1_HOFT_C02', gpsstart=1126259456.4, gpsend=1126259464.4, urltype='osdf', host='https://datafind.ligo.org', )
10:01 dingo_pipe WARNING : Failed to resolve frame files for detector L1
```
2. Now now the environment …
=> Update to bilby pipe 1.2.1

.readthedocs.yaml, pyproject.toml
This dependency is needed to generate SEOBNRv5 waveforms.
pyseobnr requires pygsl_lite, which in turn requires gsl. gsl is a non-Python package, so it is not available on pypi (although it is available on conda-forge). Consequently, for the docs to compile, we have to update .readthedocs.yaml to install gsl with apt-get.
=> Update pyproject.toml to require pyseobnr

dingo/gw/result.py, dingo/pipe/main.py
When we update data conditioning settings during importance sampling, we need to carefully update the domain objects.
There are **two** relevant domain objects in Dingo:
* The **waveform generator** domain is used first, when generating waveforms.
* The **data** domain is used when evaluating the likelihood. Waveforms generated in the `wfg_domain` must be suitably truncated, e.g., if `f_max` is reduced.
For most updates to data conditioning, we update the data domain. However, to maintain compatibility between the domains, we sometimes need to update the `wfg_domain`. This PR sets `wfg_domain.delta_f` to match that of the data domain.
Previously, we were simply using the data domain directly whenever making an update to data conditioning during importance sampling. This is clearly wrong, …
=> Choose correct `wfg_domain` during importance sampling

dingo/gw/waveform_generator/waveform_generator.py
Occasionally some waveforms fail to generate due to errors with the underlying LAL routines. The solution to this is to set np.nansfor these waveforms which will translate to np.nan later down in the pipeline. (For example when computing log likelihoods). However, the datatype of this nan array should be complex otherwise there will be places in the code like: https://github.com/dingo-gw/dingo/blob/main/dingo/gw/domains.py#L295 will trigger an error. This fixes the issue so that now if the log_likelihood of a invalid configuration is requested, np.nan will correctly be returned instead of a TypeError: https://github.com/dingo-gw/dingo/blob/main/dingo/gw/domains.py#L327
=> Changed datatype of waveforms when they fail to generate to complex

.readthedocs.yaml, dingo/core/utils/torchutils.py, dingo/gw/training/train_builders.py
This fixes a bug, where each worker was initialised with the same random seed due to a change made in [bilby](https://git.ligo.org/lscsoft/bilby/-/merge_requests/1273). 
This bug likely lead to identical samples for extrinsic parameters, which corrupted the neural network training in the following way. The network could just memorise the parameters from the previous workers, without looking at the strain data. With `N` data loader workers, this resulted in a pattern where the loss would rapidly decrease over `N` iterations, as the network memorised the parameters. In iteration `N+1`, the loss steeply increased (as all workers would generate new random numbers), and then rapidly decrease again until iteration `2N`.
=> Fix bug related to random seeds

dingo/pipe/data_generation.py, dingo/pipe/main.py, pyproject.toml
The newest MR of bilby_pipe: https://git.ligo.org/lscsoft/bilby_pipe/-/merge_requests/580/diffs?commit_id=fec7dd7f4df06c2fd2686042fd97ab7773f198af has broken the current version of dingo_pipe. This PR modifies dingo_pipe to be consistent with bilby_pipe==1.3. This would involve adding extra arguments which are required by the new version of bilby_pipe.
=> Fixing dingo_pipe to be compatible with bilby_pipe==1.3

dingo/gw/waveform_generator/waveform_generator.py
This PR fixes a bug in a NotImplementedError message.
When running importance sampling without phase marginalization and a waveform model other than IMRPhenomXPHM, a `NotImplementedError` should be hit in `generate_FD_modes_LO()` of `dingo/gw/waveform_generator/waveform_generator.py` .
However, the error message itself throws the error
`TypeError: in method 'GetApproximantFromString', argument 1 of type 'char const *'*`
in line https://github.com/dingo-gw/dingo/blob/fa032dbfb3494118868fa9ac5efd88992fbd1416/dingo/gw/waveform_generator/waveform_generator.py#L694
This error occurs because `self.approximant` is an integer while the function `LS.GetApproximantFromString(self.approximant)` only takes strings/char-type inputs.
The command is replaced by `self.approximant_str` and the error …
=> Fixed bug in NotImplementedError message

dingo/asimov/asimov.py
This MR allows bilby to automatically detect the config file template for asimov inside the python package so that it does not need to be specified as a separate template in the `asimov.conf` file.
=> Allow asimov to automatically detect the template config file

tests/gw/test_domains.py
There are failing pytests configurations which is making it so that we cannot include dingo 0.5.9 into IGWN test. This PR aims to fix the issue of the failing tests (see here: https://git.ligo.org/computing/conda/-/jobs/3268096#L1696). 
There are two failing tests currently, I am attaching the .xml of the failing tests here:
[junit-dingo-gw.txt](https://github.com/dingo-gw/dingo/files/14883697/junit-dingo-gw.txt)
The first test (`test_FD_time_translation_torch`) fails I think because the tolerance of the test is too high. It is time shifting a unit signal by 2pi and checking that it is still a unit signal. I'm not sure how the tolerance was decided. It seems like there are errors of
```
errors = torch.abs(result[..., 0, :] - torch.tensor(1.0))
errors.max() 
>> 3.0e-05
```
This happens …
=> Pytest fixes for inclusion into IGWN

dingo/core/nn/nsf.py, dingo/core/samplers.py, dingo/gw/injection.py, dingo/pipe/sampling.py, pyproject.toml, tests/core/test_nsf.py
This pull request enables support for 1 detector networks.
There are two current issues with one detector flows for Dingo.
1). https://github.com/dingo-gw/dingo/issues/216. Summarized, there is an issue when using a coupling layer with a 1D distribution with no context as there is no input to the neural network. This causes nflows to error out.
This PR fixes this by using an autoregressive flow to learn the 1D density of GNPE samples.
2). Currently, there is no way to pass no context during gibbs sampling
There is a simple fix to this which is in lines 503 of dingo.core.samplers.py.
This PR fixes the issues. It has been tested on GW190620 which is a L1 only event. It achieves a sample efficiency of 6.57% with 32_000 effective samples in this case.
=> added support for 1 detector networks

dingo/pipe/data_generation.py
In order to run summarypages on dingo and not have the "preliminary" watermark, one has to specify the PSD explicitly. However, with dingo_pipe, the PSD is saved in an event dataset which is not ingestable by bilby or pesummary. 
This PR additionally saves the PSD as a .txt file which can be passed to pesummary. An example CLI to pesummary would be 
```
summarypages --webdir ./outdir_GW150914/webpage --samples ./outdir_GW150914/dingo_importance_sampling.hdf5 --config ./outdir_GW150914/GW150914_config_complete.ini --gw --disable_expert --disable_interactive --no_ligo_skymap --psd H1:./outdir_GW150914/H1_psd.txt L1:./outdir_GW150914/L1_psd.txt
```
=> Added saving of psds as external .txt files

dingo/gw/waveform_generator/waveform_generator.py, pyproject.toml
For some reason, when stepping through `import lalsimulation.gwsignal`, the debugger hangs and is unable to step over the import. This is despite when disconnecting the debugger (or alternatively just running the file with regular python) the import works fine. 
* This fix moves the location of the import so that `lalsimulation.gwsignal` is only imported when the `NewInterfaceWaveformGenerator` is instantiated. The functions from `lalsimulation.gwsignal` are then sent to the global namespace. 
* This PR also removes pyseobnr as a required dependency for installation. You can install dingo with pyseobnr by running pip install dingo-gw[pyseobnr]. 
With conda my suggestion would be to not ship pyseobnr with dingo by default and just tell the user they need to install it on their own if they …
=> Fixing import of lalsimulation.gwsignal to allow for debuggers

docs/source/example_gnpe_model.md, docs/source/example_injection.md, docs/source/example_npe_model.md, examples/gnpe_model/train_settings.yaml, examples/npe_model/GW150914.ini
This PR fixes small bugs regarding the DINGO tutorials. The fixes include correcting typos in the docs and settings files, updating imports, correcting wrongly specified settings, and ensuring consistent naming of files and folders.
=> Correct docs of tutorials

dingo/gw/noise/generate_dataset_dag.py
This PR fixes condor_submission for generating ASD datasets
*Renamed dingo_merge_ASD_datasets to dingo_merge_asd_datasets in dag creation
=> FIxing dingo_asd_generation

dingo/pipe/dag_creator.py, dingo/pipe/utils.py
Since the bilby_pipe update, dingo_pipe was automatically adding the line `ENV GET HTGETTOKENOPTS` in the main `dag_GWxxxxxx.submit`. This line is part of the LIGO authentication ([see LIGO documentation](https://lscsoft.docs.ligo.org/bilby_pipe/v1.3.0/data_acquisition.html)), resulting in an error for `simple-submission=True`.
This PR removes the line for simple submission.
=> Fix dingo pipe simple submission

dingo/core/result.py, dingo/gw/inference/gw_samplers.py
This adds the parameters that have delta-function priors when sampling. It is needed so that the sky rotation transform and importance sampling works when holding some parameters fixed.
Corner plotting is also updated with a new flag for whether to include these fixed parameters. Default is to not include them.
**This still needs to be tested.**
=> Add fixed parameters in the GWSampler

dingo/core/models/posterior_model.py, dingo/gw/ls_cli.py, dingo/pipe/main.py
This PR addresses the problem of loading the full DINGO model just to get access to its metadata. 
PyTorch provides the option of loading a model to the ["meta" device](https://pytorch.org/docs/stable/meta.html) which allows users to load a representation of the model without loading the actual parameters into memory. As a result, we can access the metadata of the model with lower memory requirements than before.
The model is loaded to `map_location="meta"` 
- at the beginning of `dingo_pipe` where `model.metadata` is accessed
- in `ls_cli.py` where the `model.metadata` is extracted.
Loading the model to `map_location="meta"` requires changes to `dingo/core/models/posterior_model.py` since operations like `model.to(device)` and `model.load_state_dict(d["model_state_dict"])` cannot be …
=> Load model in meta state

dingo/core/result.py, dingo/core/utils/plotting.py
Upon discussion with Stephen, I changed how the truth values and truth color are passed to `result.plot_corner()` and `plot_corner_multi()`.
The reasoning behind this is the following:
- `truth_color` is included in the `**kwargs` and the description is removed since it is exactly a `corner` kwarg and does not get modified.
- `truths` is passed as a kwarg to `plot_corner_multi()`. There, `truths` needs to be a list with the values in exactly the same order as the values within `samples`. However, this order is specified within `result.plot_corner()` by the order of the `parameter` list. Therefore, we need to pass the truth values as a dictionary to `result.plot_corner()` and extract the order of parameters by replicating the order of `theta.columns`. The resulting list is added to kwargs …
=> Update plot corner (additional changes)

examples/gnpe_model/train_settings.yaml, examples/gnpe_model/train_settings_init.yaml, examples/npe_model/train_settings.yaml
The bid argument is only useful for the MPI-IS cluster so removing it from the examples.
=> Removed bid argument from examples yaml files

dingo/gw/transforms/detector_transforms.py, dingo/pipe/importance_sampling.py, dingo/pipe/parser.py, pyproject.toml
Following this bilby PR https://github.com/bilby-dev/bilby/pull/47 we can update the ApplyCalibrationUncertainty transform and dingo_pipe whether the calibration envelope is on $\eta$ or $\alpha = 1 / \eta$. Here $d = \alpha h + n$.
=> FEAT: add argument to specify calibration correction direction

dingo/core/nn/cfnets.py
Fix for this issue: https://github.com/dingo-gw/dingo/issues/277
I verified that training is now running successfully with a toy example.
=> Fix fmpe bug related to the cache

dingo/core/posterior_models/base_model.py, dingo/core/utils/trainutils.py, dingo/gw/training/train_pipeline_condor.py
This PR fixes two small bugs:
1. The argument `metric` of `EarlyStopping` does not have an effect at the moment since it is not used in the code after [initialization](https://github.com/dingo-gw/dingo-development/blob/204e43359d74fa817cf17a657c54bc52e20e5451/dingo/core/utils/trainutils.py#L55). Since it is mentioned in the example train settings files [(for example here)](https://github.com/dingo-gw/dingo/blob/11c8269aa8a76fcd51aad430822d8c8edc91d1e3/examples/fmpe_model/train_settings.yaml#L96), this might give a wrong impression to users.
A simple check for `early_stopping.metric` [here](https://github.com/dingo-gw/dingo/commit/ca79cbde9e59187f18a29db223dc411a2ef117b8#diff-e4df0a069e94766d19de6ff0aa66ff79d349e278b7a519d696e7c4c715df308bR455) which determines whether the training or test …
=> Fix bugs related to early stopping and wandb

dingo/gw/dataset/generate_dataset.py, pyproject.toml, tests/gw/test_waveform_dataset.py
- test_waveform_dataset was failing because it could not find the path to the settings file
- refactor the test to use the tempfile package
- refactored a bit the test to call a function rather than the `dingo_generate_dataset` executable
- black was called automatically on my IDE ... - - ; (we should find an agreement on formatting ?)
- The test still does not pass, it now crashes with a SegmentationFault (at this line: https://github.com/dingo-gw/dingo/blob/main/dingo/gw/SVD.py#L51)
- Other tests do not pass (unrelated to this PR)
Because of the black reformatting, it can be hard to see the significant changes. I added comment on these changes. Everything else is just formatting.
=> fixed path issue in test_waveform_dataset.py

.github/workflows/pytest.yml, pyproject.toml
Newer versions of scipy (e.g. 1.14.1) result in test_waveform_dataset.py crashing (segmentation fault).
The crash happens at this line:
https://github.com/dingo-gw/dingo/blob/main/dingo/gw/SVD.py#L51
(when sklearn.utils.extmath.randomized_svd is called).
This pull request set pyproject.toml to install scipy 1.13.1.
=> forcing scipy to 1.13.1

dingo/core/nn/nsf.py
This PR fixes this bug: https://github.com/dingo-gw/dingo/issues/283 which currently breaks the unconditional density estimation. It only does so by passing context to the embedding net when there is context.
=> Prevent FlowWrapper from using embedding net when there is no context.  

compatibility/remove_domain_window_factor.py, compatibility/update_model_input_dims.py, compatibility/update_model_metadata.py, compatibility/update_saved_model_for_train_stages.py, compatibility/update_saved_model_new_gnpe.py, compatibility/update_saved_model_new_truncation.py, dingo/core/posterior_models/base_model.py, dingo/core/posterior_models/build_model.py, dingo/core/utils/backward_compatibility.py, dingo/gw/ls_cli.py, dingo/gw/training/utils.py, tests/core/test_utils.py
The toy npe demo could not run using older version of python and cuda (e.g. python3.9 / cuda 11.3), because of poor support of the "meta" device. This pull request introduces the function 'torch_load_with_fallback' which fallback to other devices when the preferred device is not available/supported. This function attempts to fallback to cuda/mps/hip/cpu 
The code has been updated to use `torch_load_with_fallback` everywhere, not only to solve the compatibility with older version, but also for more flexibility in general.
- pytest passing (cpu / older cuda)
- toy npe demo passing (cpu/older cuda)
Not tested for mps/hip.
- Some modules in the sub-package `compatibility` where independent to the dingo package. Using `torch_load_with_fallback` them made them dependent to it. This should be …
=> using torch loading with fallback

dingo/gw/transforms/parameter_transforms.py
By accident, I encountered a failure case when training a model with a waveform dataset where one parameter is set to a fixed value (e.g. phase = 0).
If this fixed parameter is included in the list of inference parameters by accident, no error message is thrown, but the loss is NaN. The reason for this behavior is that the fixed phase parameter is divided by the std = 0 in the parameter standardization transform, resulting in NaNs.
To fix this, I included a check for `std !=0` in the standardization transform with a suitable error message.
This might not be the ideal place to throw this error. If there is a better place in the code, let me know.
=> Throw error when trying to standardize fixed parameter

dingo/pipe/importance_sampling.py
The issue is described [here](https://github.com/dingo-gw/dingo/issues/266). 
This is addressed by changing the prior before synthetic phase sampling instead of afterwards. That way, the prior doesn't default to -np.inf values and the log_likelihood and log_prob are actually evaluated. 
I tested on a GW event which was giving high evidence and low sample efficiency due to the bug and after this fix I get a reasonable evidence and 7% efficiency.
=> Fixing Issue When IS prior is broader than train prior

dingo/core/dataset.py, tests/gw/test_waveform_dataset.py
When loading dataset elements batch-wise from disk, the ordering was not maintained properly. This effectively randomized the waveforms with respect to parameters.
This PR fixes the ordering.
=> Fix bug in recursive_hdf5_load

dingo/pipe/sampling.py
Bug:
`dingo_pipe` fails in CI with the following error:
``` File "/data/dingo/venv/lib/python3.12/site-packages/dingo/pipe/sampling.py", line 115, in _load_sampler
filename=self.model, device=self.device, load_training_info=False
^^^^^^^^^^
AttributeError: 'SamplingInput' object has no attribute 'model'
```
Reason:
- An alternative path for `self.model` is required when running on OSG. This resulted in changes [when defining self.model](https://github.com/dingo-gw/dingo/blob/24685a911ade7d46ae6a8f25295597ec3306c363/dingo/pipe/sampling.py#L49)
- However, `self.model` and `self.model_init` are not defined if `args.osg is False`, leading to the CI failure.
This PR fixes this by including an `else` option.
=> fix bug introduced in cvmfs integration

dingo/gw/SVD.py, pyproject.toml
Prevent segfaults in multi-threaded LU decomposition, by switching to the QR decomposition as the normalizer for the power iteration algorithm used in randomized_svd().
The segfault happens in when applying the LU normalizer to `A @ Q` at https://github.com/scikit-learn/scikit-learn/blob/98ed9dc73/sklearn/utils/extmath.py#L335, not in the call to the standard SVD.
=> Use safer options for randomized_svd

.github/workflows/pytest.yml, dingo/gw/ls_cli.py
I ran into memory issues when trying to extract the metadata (e.g., SVD compression statistics) from a large waveform dataset with `dingo_ls`.
Explanation of the bug:
* `dingo_ls` loads the full waveform dataset into memory. This can lead to memory issues when running this command on cluster login nodes with limited memory.
Solution:
* add key `leave_waveforms_on_disk=True` to prevent waveform dataset from loading the waveforms into memory.
I tested it on our cluster and it works now.
=> leave waveforms on disk in dingo_ls for waveform datasets

dingo/gw/domains/multibanded_frequency_domain.py, tests/gw/test_mfd.py
When initializing the `MultibandedFrequencyDomain`, the minimum and maximum frequencies of the underlying `UniformFrequencyDomain` were updated to match those of the MFD. Indeed, these can differ due to boundary effects. This led to a problem where data segments prepared by dingo-pipe inadvertently had a lower maximum frequency than expected, resulting in slight evidence mismatches vs Bilby.
Remove the resetting of the UFD minimum and maximum frequencies and drop any extra bins when decimating data from UFD to MFD. In fact, no change is needed to the decimation method as it already does this.
@max-dax Check that you are happy with the updated `MultibandedFrequencyDomain` class.
@nihargupte-ph Check that you obtain consistent results with Bilby now.
=> Fix MultibandedFrequencyDomain f_max issue

dingo/gw/domains/multibanded_frequency_domain.py, dingo/gw/domains/uniform_frequency_domain.py, tests/gw/test_mfd.py, tests/gw/test_ufd.py
This is an improvement to #312.
With the previous update, the minimum and maximum frequencies of the base UniformFrequencyDomain are not updated at all. With this PR, we update them to the requested values. E.g., suppose we have
```yaml
domain:
type: MultibandedFrequencyDomain
nodes: [20.0, 33.0, 43.0, 59.0, 75.0, 107.0, 139.0, 203.0, 1099.0]
delta_f_initial: 0.125
base_domain:
type: UniformFrequencyDomain
f_min: 20.0
f_max: 1099.0
delta_f: 0.125
```
followed by
```yaml
domain_update:
f_max: 896
```
With this update, we will have `self.base_domain.f_max = 896` and `self.f_max = 890.875`. With the previous update, the base domain would have kept `f_max = 1099`.
Ultimately we want this change because it will ensure that dingo-pipe downloads data with `f_max = 896`, and that we are able to …
=> Improvements to f_min / f_max updates for MultibandedFrequencyDomain

pyproject.toml
Python==3.12.7 introduced a change to argparse, breaking the usage of mutually exclusive groups in bilby_pipe (and by extension, dingo_pipe):
* https://git.ligo.org/lscsoft/bilby_pipe/-/issues/310
=> Set maximum Python version to 3.12.6

.github/workflows/pytest.yml, dingo/gw/SVD.py
Tests are currently failing due to the fact that `scikit-learn > 1.2` no longer supports complex datatypes when generating an SVD. This change changes the default SVD to use scipy instead. One may need to run `export OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1` before generating the SVD to avoid a segfault.
=> SVD dependency issue

dingo/gw/waveform_generator/waveform_generator.py, tests/gw/waveform_generator/test_wfg.py
Hello! I started taking a look at the DINGO code to better understand the logic, and I noticed that the option to use the updated SEOBNRv5PHM model including mode asymmetries was missing (see https://arxiv.org/abs/2506.19911). These options are not turned on by default and need to be passed explicitly. This version of the model is the one that will be used for Production PE in O4b.
After checking with Nihar, I also adjusted the logic for handling extra waveform arguments, so that they are passed directly as kwargs to the `waveform_generator`.
=> Add options to enable antisymmetric modes in SEOBNRv5PHM

dingo/gw/inference/gw_samplers.py
The `MultibandedFrequencyDomain` is typically slightly below the maximum frequency of its base `UniformFrequencyDomain`. This led to an error in the check on frequency crop validity.
With this PR, we now compare against the base domain maximum frequency.
=> Fix bug in frequency crop check for MultibandedFrequencyDomain.
